publisher: "Bettercare"
publisher-url: "http://bettercare.co.za"
name: "Bettercare"
description: "Self-managed-learning coursebooks for healthcare professionals"

url: http://localhost:4000
baseurl: /bettercare
liveurl: http://ls.bettercare.co.za

paginate: 10

markdown: kramdown
permalink: none
highlighter: pygments

prose:
  siteurl: "http://electricbookworks.github.io/bettercare"
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /_site
    - /js
    - /testing
    - /images
    - robots.txt
    - .gitattributes
    - .gitignore
    - sitemap.xml