publisher: "Bettercare"
publisher-url: "http://bettercare.co.za"
name: "Bettercare"
description: "Learning programmes for empowered health professionals"

url: http://localhost:4000
baseurl: /bettercare
liveurl: http://ls.bettercare.co.za

markdown: kramdown
permalink: none
highlighter: rouge

# Jekyll will ignore these files and folders. 
# Useful for temporarily speeding up processing for particular files.
exclude: [
# BOOKS -----------------------------
# adult-hiv,
# birth-defects,
# breast-care,
# catalogue,
# child-healthcare,
# childhood-critical-care,
# childhood-hiv,
# childhood-tb,
# chw-sample,
# ebola-prevention-and-control,
# facilitators-guide,
# infection-prevention-and-control,
# intrapartum-care,
# maternal-care,
# maternal-mental-health,
# mother-and-baby-friendly-care,
# newborn-care,
# perinatal-hiv,
# primary-maternal-care,
# primary-newborn-care,
# saving-mothers-and-babies,
# well-women,
# ADMIN FILES -----------------------------
# _book-template,
# admin,
# css,
# images,
# js,
# maintenance.html,
# README.md,
# robots.txt,
# sitemap.xml,
# _bqf,
# _includes,
# _layouts,
# _site,
# css,
]

# Defaults
# These are default YAML values that apply to multiple documents. 
# (For technical details, see http://jekyllrb.com/docs/configuration/#front-matter-defaults).
defaults: 
    -
        scope: # First we set defaults for all files in this series folder (an empty string "" for path means all files).
            path: ""
        values:
            language: "en"
            layout: "chapter"
            stylesheet-print: "print.css"
            stylesheet-web: "screen.css"
            stylesheet-epub: "epub.css"
            contents: "0-3-contents.html"
            language: "en"
            images-folder: images

